"use client";
import { useState } from "react";

type Story={id:string;title:string;subtitle:string;time:number;tone:string;intro:string;body:string[];lesson:string};
const stories:Story[]=[
{id:"butter",title:"The Butter Thief",subtitle:"A playful tale from Gokul",time:3,tone:"gold",intro:"A little mischief, a lot of butter, and a mother’s endless love.",body:["In Gokul lived a bright, curious boy named Krishna. He loved his friends, his flute—and fresh butter most of all.","The village mothers hung their butter pots high. Krishna and his friends made a human ladder, climbed up carefully, and shared the butter with delighted smiles.","When Mother Yashoda caught him, his cheeks told the story. She tried to look stern, but love won."],lesson:"Love can hold both laughter and correction. Krishna’s playfulness reminds us to keep joy alive."},
{id:"kaliya",title:"Dancing on Kaliya",subtitle:"Courage by the Yamuna",time:4,tone:"teal",intro:"When fear entered the river, young Krishna answered with courage.",body:["A serpent named Kaliya had made the Yamuna unsafe. The people of Vrindavan were frightened.","Krishna leapt into the water and calmly danced upon Kaliya’s many hoods until the serpent’s pride softened.","Krishna spared Kaliya and asked him to leave in peace. The water became clear again."],lesson:"Real strength does not need cruelty. It protects others and leaves room for change."},
{id:"govardhan",title:"Lifting Govardhan",subtitle:"Shelter beneath a mountain",time:5,tone:"blue",intro:"One little finger. One great mountain. A whole village kept safe.",body:["Dark clouds gathered over Vrindavan, bringing a storm unlike any the villagers had seen.","Krishna lifted Govardhan Hill with one finger and invited every person and animal to shelter beneath it.","The storm passed. Krishna gently set the hill back, teaching everyone that care for the earth and one another is sacred."],lesson:"When we use our strength to shelter others, even the heaviest burden becomes meaningful."},
{id:"flute",title:"The Song of the Flute",subtitle:"An evening in Vrindavan",time:3,tone:"rose",intro:"A quiet story about listening to what brings the heart peace.",body:["At dusk, Krishna sat beneath a kadamba tree and raised his flute.","The cows stopped grazing. Friends paused their work. Even the leaves seemed to listen.","Krishna’s music simply reminded everyone to be present for the beauty already around them."],lesson:"Stillness helps us notice wonder. A peaceful heart can hear what noise often hides."},
{id:"sudama",title:"Krishna & Sudama",subtitle:"A friendship remembered",time:6,tone:"sand",intro:"A humble gift shows that true friendship never measures wealth.",body:["Sudama travelled to meet his childhood friend carrying only a small bundle of flattened rice.","Krishna welcomed him with warmth and accepted the simple gift as though it were treasure.","Sudama returned home knowing sincere love was richer than any grand offering."],lesson:"A gift is made precious by the love within it, not by its price."},
{id:"universe",title:"The Universe Within",subtitle:"Yashoda’s moment of wonder",time:4,tone:"violet",intro:"Mother Yashoda sees more than she ever imagined.",body:["Krishna’s friends told Yashoda that he had eaten earth. She asked him to open his mouth.","There she saw sky, stars, rivers, mountains, and every living being.","For a moment she stood in wonder. Then Krishna smiled, and she gathered him into her arms."],lesson:"The sacred can be close, hidden inside the ordinary moments we love."}
];
const wisdom=[
{theme:"Action",ref:"Bhagavad Gita 2.47",quote:"Focus on the work in front of you, not on controlling its reward.",meaning:"Give your best to what you can do today. Your effort and intention are yours."},
{theme:"Calm",ref:"Bhagavad Gita 2.70",quote:"Peace comes when every passing desire does not pull us away.",meaning:"We become steadier when every wish does not decide our mood."},
{theme:"Change",ref:"Bhagavad Gita 2.22",quote:"As we change old clothes for new, the soul moves through change.",meaning:"Life keeps changing. Our deepest self is larger than any one season."},
{theme:"Kindness",ref:"Bhagavad Gita 12.13",quote:"One who is friendly, compassionate, and free from hatred is dear to me.",meaning:"Spiritual growth is visible in how gently we treat people."}
];
const dailyWisdom=wisdom[Math.floor(Date.now()/86400000)%wisdom.length];
const paths:Record<string,React.ReactNode>={feather:<><path d="M20 3C12 2 6 7 6 13c0 3 2 5 5 6 5-3 8-9 9-16Z"/><path d="M4 22C8 16 12 11 18 7"/></>,book:<><path d="M4 5a3 3 0 0 1 3-3h4v19H7a3 3 0 0 0-3 3Z"/><path d="M20 5a3 3 0 0 0-3-3h-4v19h4a3 3 0 0 1 3 3Z"/></>,home:<><path d="m3 11 9-8 9 8"/><path d="M5 10v11h14V10"/></>,star:<path d="m12 2 1.4 4.6L18 8l-4.6 1.4L12 14l-1.4-4.6L6 8l4.6-1.4Z"/>,heart:<path d="M20.8 5.7a5.5 5.5 0 0 0-7.8 0l-1 1.1-1.1-1.1a5.5 5.5 0 1 0-7.8 7.8L12 22l8.8-8.5a5.5 5.5 0 0 0 0-7.8Z"/>,sound:<><path d="M6 10H3v4h3l4 4V6Z"/><path d="M14 9a4 4 0 0 1 0 6M17 6a8 8 0 0 1 0 12"/></>,clock:<><circle cx="12" cy="12" r="9"/><path d="M12 7v5l3 2"/></>,arrow:<><path d="M5 12h14"/><path d="m14 7 5 5-5 5"/></>,user:<><circle cx="12" cy="8" r="4"/><path d="M4 21a8 8 0 0 1 16 0"/></>};
function Icon({name,size=20}:{name:string;size?:number}){return <svg aria-hidden="true" width={size} height={size} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.7" strokeLinecap="round" strokeLinejoin="round">{paths[name]}</svg>}
function Art({story,big=false}:{story:Story;big?:boolean}){return <div className={"art "+story.tone+(big?" big":"")}><i/><span className={"motif "+story.id}/><b>· ✦ ·</b></div>}
export default function Home(){
 const[view,setView]=useState("home"),[selected,setSelected]=useState<Story|null>(null),[saved,setSaved]=useState<string[]>([]),[filter,setFilter]=useState("All"),[quiz,setQuiz]=useState(false),[toast,setToast]=useState("");
 const daily=dailyWisdom;
 const go=(v:string)=>{setView(v);setSelected(null);window.scrollTo({top:0,behavior:"smooth"})};
 const save=(id:string)=>setSaved(x=>x.includes(id)?x.filter(y=>y!==id):[...x,id]);
 const tell=(m:string)=>{setToast(m);setTimeout(()=>setToast(""),2200)};
 const speak=(t:string)=>{if(!("speechSynthesis" in window)){tell("Audio is not available here.");return}speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(t);u.rate=.88;speechSynthesis.speak(u);tell("Reading aloud…")};
 const Card=({s}:{s:Story})=><button className="story-card" onClick={()=>setSelected(s)}><Art story={s}/><div><small>ALL AGES <span><Icon name="clock" size={13}/>{s.time} MIN</span></small><h3>{s.title}</h3><p>{s.intro}</p><b>Read the story <Icon name="arrow" size={15}/></b></div></button>;
 if(selected)return <main><header className="topbar detailbar"><button className="circle back" onClick={()=>setSelected(null)}><Icon name="arrow"/></button><Brand/><button className={"circle "+(saved.includes(selected.id)?"saved":"")} onClick={()=>save(selected.id)}><Icon name="heart"/></button></header><article className="reader"><div className="reader-art"><Art story={selected} big/><small><Icon name="feather" size={15}/> A LITTLE KRISHNA STORY</small></div><div className="reader-copy"><p className="eyebrow">{selected.subtitle}</p><h1>{selected.title}</h1><p className="intro">{selected.intro}</p><div className="meta"><Icon name="clock" size={16}/>{selected.time} MIN READ · ALL AGES</div><button className="listen" onClick={()=>speak(selected.title+". "+selected.body.join(" ")+" "+selected.lesson)}><span><Icon name="sound"/></span><b>Listen to the story<small>Gentle narration · {selected.time} minutes</small></b></button><div className="prose">{selected.body.map((p,i)=><p className={i===0?"first":""} key={p}>{p}</p>)}</div><aside className="lesson"><Icon name="feather"/><div><b>CARRY THIS WITH YOU</b><p>{selected.lesson}</p></div></aside><button className="primary wide" onClick={()=>{tell("A peacock feather was added!");setSelected(null)}}>I finished this story <Icon name="star"/></button></div></article>{toast&&<Toast text={toast}/>}</main>;
 return <main><header className="topbar"><Brand/><nav>{[["home","Home"],["stories","Stories"],["gita","Gita, simply"],["kids","For kids"]].map(x=><button className={view===x[0]?"active":""} onClick={()=>go(x[0])} key={x[0]}>{x[1]}</button>)}</nav><div className="head"><span>✦ 7 day journey</span><button className="circle" onClick={()=>go("profile")}><Icon name="user" size={18}/></button></div></header>
 {view==="home"&&<><section className="hero"><div><p className="eyebrow light">— A quiet moment with Krishna</p><h1>Ancient wisdom.<br/><em>Beautifully simple.</em></h1><p>Discover little Krishna’s stories and the heart of the Bhagavad Gita—in words that feel warm, clear, and close to home.</p><div className="hero-buttons"><button className="primary" onClick={()=>setSelected(stories[0])}>Begin with a story <Icon name="arrow"/></button><button onClick={()=>go("gita")}>Explore the Gita ↗</button></div><small>MADE FOR EVERY CURIOUS HEART · NO SANSKRIT NEEDED</small></div><div className="peacock"><div className="rings"/><div className="feather-shape"><i/><span/>{Array.from({length:9}).map((_,i)=><b key={i} style={{"--n":i} as React.CSSProperties}/>)}</div><aside><small>TODAY’S GENTLE REMINDER</small>“Let your work be your offering.”</aside></div></section><section className="daily"><article><div>— <Icon name="star"/> —</div><p className="eyebrow">A thought for today</p><blockquote>“{daily.quote}”</blockquote><p>In simple words: {daily.meaning}</p><footer><span>{daily.ref}</span><div><button onClick={()=>speak(daily.quote+". "+daily.meaning)}><Icon name="sound" size={17}/>Listen</button><button className={saved.includes("daily")?"saved":""} onClick={()=>save("daily")}><Icon name="heart" size={17}/>{saved.includes("daily")?"Saved":"Save"}</button></div></footer></article></section><section className="content"><Heading eyebrow="Begin with wonder" title="Little Krishna stories" action={()=>go("stories")}/><div className="story-grid">{stories.slice(0,4).map(s=><Card s={s} key={s.id}/>)}</div></section><section className="wisdom-band"><div><span className="medal"><Icon name="feather"/></span><p className="eyebrow light">Gita wisdom, simply put</p><h2>Big questions.<br/>Clear, gentle answers.</h2><p>Explore what Krishna says about fear, purpose, change, anger, and finding peace.</p><button className="cream" onClick={()=>go("gita")}>Explore simple wisdom <Icon name="arrow"/></button></div><div className="wisdom-stack">{wisdom.slice(0,3).map((w,i)=><button key={w.ref} style={{"--r":(i*1.6-1.6)+"deg"} as React.CSSProperties} onClick={()=>go("gita")}><span>{w.theme}</span><b>“{w.quote}”</b><small>{w.ref}<Icon name="arrow" size={14}/></small></button>)}</div></section><section className="kids-preview"><div className="rainbow"><i/><i/><i/><Icon name="feather" size={48}/></div><div><span>FOR LITTLE LISTENERS</span><h2>Stories they’ll ask for again.</h2><p>Short bedtime tales, playful lessons, and tiny activities made for curious kids and their grown-ups.</p><ul><li>Age-friendly stories</li><li>Listen-aloud mode</li><li>Gentle life lessons</li></ul><button className="primary" onClick={()=>go("kids")}>Visit kids’ corner <Icon name="arrow"/></button></div></section></>}
 {view==="stories"&&<section className="page content"><PageTitle eyebrow="From Gokul to Dwarka" title="Stories to carry with you." text="Small adventures, enduring friendships, and gentle lessons—told in clear, welcoming English."/><div className="story-grid library">{stories.map(s=><Card s={s} key={s.id}/>)}</div></section>}
 {view==="gita"&&<section className="page content"><PageTitle eyebrow="The Gita, without the overwhelm" title="Wisdom for real life." text="Choose what is on your mind. Each teaching has a clear meaning and one small way to live it today."/><div className="filters">{["All",...wisdom.map(w=>w.theme)].map(x=><button className={filter===x?"active":""} onClick={()=>setFilter(x)} key={x}>{x}</button>)}</div><div className="gita-list">{wisdom.filter(w=>filter==="All"||w.theme===filter).map((w,i)=><article key={w.ref}><strong>0{i+1}</strong><div><p className="eyebrow">On {w.theme.toLowerCase()}</p><h2>“{w.quote}”</h2><p>{w.meaning}</p><aside><b>TRY THIS TODAY</b> Before your next task, take one breath and decide what “doing it with care” looks like.</aside></div><footer><span>{w.ref}</span><button onClick={()=>speak(w.quote+". "+w.meaning)}><Icon name="sound"/></button><button className={saved.includes(w.ref)?"saved":""} onClick={()=>save(w.ref)}><Icon name="heart"/></button></footer></article>)}</div><p className="source">Approachable paraphrases for learning—not literal Sanskrit translations.</p></section>}
 {view==="kids"&&<section className="page content"><div className="kids-hero"><div><span>KIDS’ CORNER</span><h1>Hi, little friend!</h1><p>Ready for a tiny Krishna adventure?</p></div><Icon name="feather" size={92}/></div><div className="kids-grid"><article className="bedtime"><div><p>TONIGHT’S BEDTIME STORY</p><h2>The Song of the Flute</h2><small>3 minutes · soft narration</small><button onClick={()=>setSelected(stories[3])}><Icon name="sound"/> Let’s listen</button></div><Art story={stories[3]}/></article><article className="quiz"><p>LITTLE QUIZ</p><h2>{quiz?"That’s right—fresh butter!":"What did Krishna love to share with his friends?"}</h2>{quiz?<button onClick={()=>setQuiz(false)}>Play again</button>:<div>{["Butter","Books","Mangoes"].map(a=><button onClick={()=>a==="Butter"?setQuiz(true):tell("Nice try! Think of Gokul.")} key={a}>{a}</button>)}</div>}</article></div></section>}
 {view==="profile"&&<section className="page profile"><article><div><Icon name="feather" size={32}/></div><p className="eyebrow light">Your quiet corner</p><h1>Welcome back.</h1><p>Every story is a small step inward.</p><footer><span><b>7</b>day journey</span><span><b>4</b>stories read</span><span><b>{saved.length}</b>saved pieces</span></footer></article><section><Heading eyebrow="Your collection" title="Saved for later"/>{saved.length===0?<div className="empty"><Icon name="heart" size={28}/><b>Nothing saved yet.</b><p>Tap a heart beside a teaching to keep it here.</p></div>:saved.map(id=><div className="saved-row" key={id}><Icon name="feather"/><b>{wisdom.find(w=>w.ref===id)?.theme||"Thought for today"}</b><button onClick={()=>save(id)}>×</button></div>)}</section></section>}
 <nav className="mobile">{[["home","home","Home"],["stories","book","Stories"],["gita","feather","Gita"],["kids","star","Kids"],["profile","user","You"]].map(x=><button className={view===x[0]?"active":""} onClick={()=>go(x[0])} key={x[0]}><Icon name={x[1]} size={20}/><span>{x[2]}</span></button>)}</nav><footer className="site-footer"><Brand/><p>Stories that bring ancient wisdom a little closer.</p><small>MADE WITH CARE FOR CURIOUS HEARTS.</small></footer>{toast&&<Toast text={toast}/>}</main>
}
function Brand(){return <div className="brand"><span><Icon name="feather" size={18}/></span>Leela <small>STORIES OF KRISHNA</small></div>}
function Heading({eyebrow,title,action}:{eyebrow:string;title:string;action?:()=>void}){return <div className="heading"><div><p className="eyebrow">{eyebrow}</p><h2>{title}</h2></div>{action&&<button onClick={action}>See all stories <Icon name="arrow" size={17}/></button>}</div>}
function PageTitle({eyebrow,title,text}:{eyebrow:string;title:string;text:string}){return <div className="page-title"><p className="eyebrow">{eyebrow}</p><h1>{title}</h1><p>{text}</p></div>}
function Toast({text}:{text:string}){return <div className="toast"><Icon name="star" size={17}/>{text}</div>}
